#!/usr/bin/env bash
set -euo pipefail
IFS='\n\t'

#
# mount necessary directories before chroot and unmount them after chroot
#

CHROOT="$1"; shift

if [[ "$EUID" -ne 0 ]]
then
	echo "Please run as root"
	exit
fi

if [[ -z "$CHROOT" ]]
then
	echo "You have to specify chroot directory."
	exit
fi

if [[ ! -d "$CHROOT" ]]
then
	echo "Directory $CHROOT doesn't exist."
	exit
fi

mount --bind /proc "${CHROOT}"/proc
mount --bind /sys "${CHROOT}"/sys
mount --bind /dev "${CHROOT}"/dev
mount --bind /dev/pts "${CHROOT}"/dev/pts

echo "Prechroot commands are successfully executed."

chroot "$CHROOT" "$@"

umount "${CHROOT}"/dev/pts
umount "${CHROOT}"/dev
umount "${CHROOT}"/sys
umount "${CHROOT}"/proc

echo "Postchroot commands are successfully executed."
